-- bike-my-day initial schema
--
-- Three tables, all owned by an authenticated user (user_id = auth.uid()):
--   rides                  recurring bike trips the user wants verdicts for
--   notification_channels  per-user delivery destinations (email, webpush, native)
--   notifications          one row per (ride, scheduled_for) — generated by the
--                          cron worker; the unique dedupe_key makes the worker
--                          idempotent on retries.

set search_path = public;

create extension if not exists pgcrypto;

-- updated_at helper -----------------------------------------------------------

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- rides -----------------------------------------------------------------------

create table public.rides (
  id                 uuid primary key default gen_random_uuid(),
  user_id            uuid not null references auth.users(id) on delete cascade,
  label              text not null,
  start_address      text not null,
  start_lat          double precision not null,
  start_lon          double precision not null,
  end_address        text not null,
  end_lat            double precision not null,
  end_lon            double precision not null,
  depart_local_time  time not null,
  days_of_week       smallint[] not null
                       check (array_length(days_of_week, 1) between 1 and 7
                              and days_of_week <@ array[0,1,2,3,4,5,6]::smallint[]),
  timezone           text not null,
  active             boolean not null default true,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);

create index rides_user_id_active_idx on public.rides (user_id) where active;

create trigger rides_set_updated_at
  before update on public.rides
  for each row execute function public.set_updated_at();

-- notification_channels -------------------------------------------------------

create type public.notification_kind as enum ('email', 'webpush', 'native');

create table public.notification_channels (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid not null references auth.users(id) on delete cascade,
  kind         public.notification_kind not null,
  destination  jsonb not null,
  verified     boolean not null default false,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create index notification_channels_user_idx on public.notification_channels (user_id);

create trigger notification_channels_set_updated_at
  before update on public.notification_channels
  for each row execute function public.set_updated_at();

-- notifications ---------------------------------------------------------------

create table public.notifications (
  id              uuid primary key default gen_random_uuid(),
  user_id         uuid not null references auth.users(id) on delete cascade,
  ride_id         uuid not null references public.rides(id) on delete cascade,
  channel_id      uuid references public.notification_channels(id) on delete set null,
  scheduled_for   timestamptz not null,
  forecast_json   jsonb,
  verdict_text    text,
  score           smallint,
  sent_at         timestamptz,
  dedupe_key      text generated always as
                    (ride_id::text || '|' || to_char(scheduled_for at time zone 'utc',
                                                     'YYYY-MM-DD"T"HH24:MI:SSZ')) stored,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  unique (dedupe_key)
);

create index notifications_user_scheduled_idx
  on public.notifications (user_id, scheduled_for desc);

create trigger notifications_set_updated_at
  before update on public.notifications
  for each row execute function public.set_updated_at();

-- Row Level Security ----------------------------------------------------------

alter table public.rides                 enable row level security;
alter table public.notification_channels enable row level security;
alter table public.notifications         enable row level security;

-- rides: owner has full CRUD
create policy "rides: owner read"   on public.rides for select using (user_id = auth.uid());
create policy "rides: owner insert" on public.rides for insert with check (user_id = auth.uid());
create policy "rides: owner update" on public.rides for update using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "rides: owner delete" on public.rides for delete using (user_id = auth.uid());

-- notification_channels: owner has full CRUD
create policy "channels: owner read"   on public.notification_channels for select using (user_id = auth.uid());
create policy "channels: owner insert" on public.notification_channels for insert with check (user_id = auth.uid());
create policy "channels: owner update" on public.notification_channels for update using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "channels: owner delete" on public.notification_channels for delete using (user_id = auth.uid());

-- notifications: owner can read their own; writes are reserved for the
-- service-role cron worker (which bypasses RLS), so no INSERT/UPDATE policy
-- is granted to authenticated users.
create policy "notifications: owner read" on public.notifications for select using (user_id = auth.uid());
